name: LaTeX-to-PDF

on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Compile LaTeX document
        uses: QED137/latex-action@v2
        with:
          root_file: EssentialStatistics/book.tex

      - name: Copy file
        run: |
          sudo mv EssentialStatistics/book.pdf .

      - name: Deploy to gh-pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: EssentialStatistics
